require("plugins.lsp")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.treesitter")
-- require("plugins.nvimtree")
require("plugins.autopairs")
require("plugins.gitsigns")
require("plugins.statusline")
-- require("plugins.toggleterm")
-- require("plugins.clangd")
require("plugins.cmp")
require("plugins.hdl")
-- require("plugins.nullls")
-- require("plugins.project")
require("plugins.indent")
require("plugins.dap")
-- require("plugins.neotest")
-- require("plugins.trouble")
