-- init.lua

require('settings')
require('maps')
require('plugins')
require('config/nvimtree')
require('config/statusline')
require('config/visual')
require('config/lsp')
require('config/treesitter')
require('config/cmp')
require('config/telescope')
require('config/gitsigns')
require('config/lualine')
require('config/hdl')
require('config/autopairs')
require('config/toggleterm')
require('config/project')
