#     _    _                 _ _____ _______   __
#    / \  | | __ _  ___ _ __(_)_   _|_   _\ \ / /
#   / _ \ | |/ _` |/ __| '__| | | |   | |  \ V /
#  / ___ \| | (_| | (__| |  | | | |   | |   | |
# /_/   \_\_|\__,_|\___|_|  |_| |_|   |_|   |_|
#
#
# Configuration for Alacritty, the GPU enhanced terminal emulator.
# See this wiki page for more info:
# https://github.com/jwilm/alacritty/wiki


# Window configuration
window:
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 0
    y: 0

  dynamic_padding: false
  decorations: none
  startup_mode: Windowed


scrolling:
  history: 10000
  multiplier: 3

# Font configuration
font:
  normal:
    family: Hack Nerd Font
    style: Regular

  bold:
    family: Hack Nerd Font
    style: Bold

  italic:
    family: Hack Nerd Font
    style: Italic

  size: 11

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  scale_with_dpi: true
  use_thin_strokes: false

draw_bold_text_with_bright_colors: true

# Colors (Dracula)
colors:
  # Default colors
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xcaa9fa'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xbfbfbf'

  # Bright colors
  bright:
    black:   '0x282a35'
    red:     '0xff6e67'
    green:   '0x5af78e'
    yellow:  '0xf4f99d'
    blue:    '0xcaa9fa'
    magenta: '0xff92d0'
    cyan:    '0x9aedfe'
    white:   '0xe6e6e6'

# # Colors (Blood Moon)
# colors:
#   # Default colors
#   primary:
#     background: '0x10100E'
#     foreground: '0xC6C6C4'

#   # Normal colors
#   normal:
#     black:   '0x10100E'
#     red:     '0xC40233'
#     green:   '0x009F6B'
#     yellow:  '0xFFD700'
#     blue:    '0x0087BD'
#     magenta: '0x9A4EAE'
#     cyan:    '0x20B2AA'
#     white:   '0xC6C6C4'

#   # Bright colors
#   bright:
#     black:   '0x696969'
#     red:     '0xFF2400'
#     green:   '0x03C03C'
#     yellow:  '0xFDFF00'
#     blue:    '0x007FFF'
#     magenta: '0xFF1493'
#     cyan:    '0x00CCCC'
#     white:   '0xFFFAFA'


# Visual bell
bell:
  animation: EaseOutExpo
  duration: 0

# background_opacity: 0.85

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  faux_scrolling_lines: 1
  hide_when_typing: true

cursor:
  style: Block
  unfocused_hollow: true

window.dynamic_title: true

live_config_reload: true

shell:
  program: /bin/zsh
  # args:
  #  - -l
  #  - -c
  #  - "tmux"

#key_bindings:
#  - { key: V,         mods: Alt,        action: Paste                        }
#  - { key: Y,         mods: Alt,        action: Copy                         }
#  - { key: Insert,    mods: Shift,      action: PasteSelection               }
#  - { key: Key0,      mods: Control,    action: ResetFontSize                }
#  - { key: Equals,    mods: Control,    action: IncreaseFontSize             }
#  - { key: Add,       mods: Control,    action: IncreaseFontSize             }
#  - { key: Subtract,  mods: Control,    action: DecreaseFontSize             }
#  - { key: Minus,     mods: Control,    action: DecreaseFontSize             }
#  - { key: Return,    mods: Alt,        action: ToggleFullscreen             }
#  - { key: Paste,                       action: Paste                        }
#  - { key: Copy,                        action: Copy                         }
#  - { key: L,         mods: Control,    action: ClearLogNotice               }
#  - { key: L,         mods: Control,    chars: "\x0c"                        }
#  - { key: PageUp,    mods: Shift,      action: ScrollPageUp,   mode: ~Alt   }
#  - { key: PageDown,  mods: Shift,      action: ScrollPageDown, mode: ~Alt   }
#  - { key: Home,      mods: Shift,      action: ScrollToTop,    mode: ~Alt   }
#  - { key: End,       mods: Shift,      action: ScrollToBottom, mode: ~Alt   }


